#!/usr/bin/env bash 
exec > >(tee -a h5mc.log)

echo "h5get begin `date`"

# turn on better logging
set -x
SYM=`basename $PWD`
echo "Symbol to fetch, based on directory name: $SYM"

#mython yahoo "$SYM" > raw.dat

ydec "$SYM"
mv "$SYM" raw.dat

set +x
echo "h5get end"
echo
exit 0
