program rs6
  use fgsl
  use iso_c_binding
  implicit none

  integer, parameter:: mrows = 1000
  double precision, dimension(mrows) :: rs6mb, sorted
  double precision::  decs(0:10), inp
  !integer::i
  integer (c_size_t) :: i, n, accepted, idx(mrows)
  character (len=10) :: epic(mrows)
  character(len=30) :: date


  
  open(unit=11, file='_count', action = 'read')
  read(unit=11, fmt='(I5)'), n
  close(11)
  !print *, n
  !stop
  
  open(unit = 11, file = 'rs6mb', action = 'read')
  read(unit = 11, fmt = *) rs6mb(1:n) ! read even the Nans
  close(11)
  

  !subset only valid inputs
  accepted = 0
  !sorted = rs6mb
  do i = 1 ,n
     if(.not.isnan(rs6mb(i))) then
        accepted = accepted +1
        sorted(accepted) = rs6mb(i)
     endif
  enddo
  
  ! sort and calculate deciles  
  call fgsl_sort(sorted(1:accepted), 1_fgsl_size_t, accepted)
  !print *, sorted(1:accepted)
  
  do i=0,10
     decs(i) = fgsl_stats_quantile_from_sorted_data(sorted, 1_fgsl_size_t, n, dble(i)/dble(10.0))
  enddo


  

  ! read epics
  open(unit=11, file='epic', action= 'read')
  read (unit=11, fmt='(A4)') , epic(1:n)
  close(11)

  ! print percentiles
  print *, "rs6mb ordered in percentiles"
  write (*,fmt='(A1,x,A7,x,A5,x,A7)'), "H", "p'ile", "epic", "rs6mb"
  call fgsl_sort_index(idx, rs6mb, 1_fgsl_size_t, n)
  do i=1,n
     write(*,fmt='(A1, f7.2, 1x, A5, f7.2)') , '1', dble(100) * dble(i-1)/dble(n), epic(idx(i)+1), &
          & rs6mb(idx(i)+1)
  enddo

  
  !print deciles
  print *, "rs6mb by deciles"
  do i = 0,10
     print *, dble(i)/dble(10.), decs(i)
  enddo
  print *, "Number of accepted:", accepted
  print *, "Number of rejects: ", n - accepted
  print *, "Toatal inputs:     ", n

  
  ! print the good ones
  print *, "Epics in the top decile:"
  do i=1, n
     if((.not.isnan(rs6mb(i))) .and. (rs6mb(i).ge.decs(9))) write(*, fmt='(A)',advance='no') epic(i)
  enddo
  print *
  !print *, epic(1:n)
  print *

  call fdate(date)
  print *, "Generated by rs6 from h5mc git on ", date
  print *, "Try doing rs6 >calcs/rs6mb.rs6"
end program rs6
