program rs6
  use fgsl
  use iso_c_binding
  implicit none
  
  double precision :: decs(0:10), rs6mb(1:1000), sorted(1:1000), inp
  !integer::i
  integer (c_size_t) :: i, n, accepted
  character (len=10) :: epic(1:1000)
  character(len=30) :: date

  print *, "rs6mb by deciles"
  
  open(unit=11, file='_count', action = 'read')
  read(unit=11, fmt='(I5)'), n
  close(11)
  !print *, n
  !stop
  
  open(unit = 11, file = 'rs6mb', action = 'read')
  read(unit = 11, fmt = *) rs6mb(1:n) ! read even the Nans
  close(11)
  

  !subset only valid inputs
  accepted = 0
  !sorted = rs6mb
  do i = 1 ,n
     if(.not.isnan(rs6mb(i))) then
        accepted = accepted +1
        sorted(accepted) = rs6mb(i)
     endif
  enddo
  
  ! sort and calculate deciles  
  call fgsl_sort(sorted(1:accepted), 1_fgsl_size_t, accepted)
  !print *, sorted(1:accepted)
  
  do i=0,10
     decs(i) = fgsl_stats_quantile_from_sorted_data(sorted, 1_fgsl_size_t, n, dble(i)/dble(10.0))
  enddo

  !print results
  do i = 0,10
     print *, dble(i)/dble(10.), decs(i)
  enddo
  print *, "Number of accepted:", accepted
  print *, "Number of rejects: ", n - accepted
  print *, "Toatal inputs:     ", n
  

  ! read epics
  open(unit=11, file='epic', action= 'read')
  read (unit=11, fmt='(A4)') , epic(1:n)
  close(11)

  ! print the good ones
  print *, "Epics in the top decile:"
  do i=1, n
     if((.not.isnan(rs6mb(i))) .and. (rs6mb(i).ge.decs(9))) write(*, fmt='(A)',advance='no') epic(i)
  enddo
  print *
  !print *, epic(1:n)
  print *

  call fdate(date)
  print *, "Generated by rs6 from h5mc git on ", date
  print *, "Try doing rs6 >calcs/rs6mb.rs6"
end program rs6
